version: "3.9"

services:
  web:
    build: .
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
